# Generated by Django 2.2.4 on 2019-10-30 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(choices=[('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING')], max_length=8, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=500, verbose_name='Detalhes')),
                ('number_events', models.IntegerField(verbose_name='Quantidade de Eventos')),
                ('occurrence_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Ocorrência')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Environment')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Level')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Origin')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
